Repository CorvusOps/e-Marka, pull requests merged in 2021-02, with the labels that each got.

#1 initial commit on planned files
  Lib/.gitignore
  Lib/src/connection/DatabaseConnection.java
  Lib/src/gui/FrameMain.java
  Lib/src/gui/entity/component/DialogCreatePerformanceTask.java
  Lib/src/gui/entity/component/DialogCreateQuarterlyAssessment.java
  Lib/src/gui/entity/component/DialogCreateWrittenWorks.java
  Lib/src/gui/entity/component/PanelComponentManagement.java
  Lib/src/gui/entity/component/TemplatePerformanceTasks.java
  Lib/src/gui/entity/component/TemplateQuarterlyAssessment.java
  Lib/src/gui/entity/component/TemplateWrittenWorks.java
  Lib/src/gui/entity/grade/PanelGradeManagement.java
  Lib/src/gui/entity/student/DialogCreateStudent.java
  Lib/src/gui/entity/student/DialogUpdateStudent.java
  Lib/src/gui/entity/student/PanelStudentManagement.java
  Lib/src/gui/entity/student/TemplateStudent.java
  Lib/src/gui/entity/subject/PanelSubjectManagement.java
  Lib/src/gui/entry/LogIn.java
Labels: good first issue

#2 Add domain
  Lib/src/domain/Student.java
  Lib/src/domain/Subject.java
Labels: good first issue

#3 Add initial repository
  Lib/src/repository/CRUDStudent.java
  Lib/src/repository/CRUDSubject.java
Labels: good first issue

#4 Update student GUI
  Lib/src/gui/entity/student/DialogCreateStudent.java
  Lib/src/gui/entity/student/DialogUpdateStudent.java
  Lib/src/gui/entity/student/PanelStudentManagement.java
  Lib/src/gui/entity/student/TemplateStudent.java
Labels: enhancement

#5 Update MainFrame Version 1.1
  Lib/src/gui/FrameMain.java
Labels: enhancement

#10 Update Create Dialog of Performance Task
  Lib/src/gui/entity/component/DialogCreatePerformanceTasks.java
Labels: bug

#26 Add DialogCreateWrittenWorks.java
  Lib/src/gui/entity/component/DialogCreatePerformanceTasks.java
  Lib/src/gui/entity/component/DialogCreateQuarterlyAssessment.java
  Lib/src/gui/entity/component/DialogCreateWrittenWorks.java
Labels: good first issue

#24 Add DialogCreatePerformanceTasks.java
  Lib/src/gui/entity/component/DialogCreatePerformanceTasks.java
Labels: good first issue

#38 add PanelComponentManagement
  Lib/src/gui/entity/component/PanelComponentManagement.java
Labels: good first issue

#37 Tablemodel
  Lib/src/gui/entity/grade/PanelGradeManagement.java
  Lib/src/gui/entity/grade/PanelStudentManagement.java
  Lib/src/gui/entity/grade/TemplateGrade.java
Labels: good first issue

#35 add PanelGradeManagement.java
  Lib/src/gui/entity/grade/PanelGradeManagement.java
  Lib/src/gui/entity/grade/PanelStudentManagement.java
Labels: good first issue

#40 Dialog pt
  Lib/src/gui/entity/component/DialogCreatePT.java
Labels: enhancement

#41 Dialog qa
  Lib/src/gui/entity/component/DialogCreateQA.java
Labels: enhancement

#43 PANEL COMPONENT PT
  Lib/src/gui/entity/component/PanelComponentPT.java
Labels: enhancement

#42 Dialog ww
  Lib/src/gui/entity/component/DialogCreateWW.java
Labels: enhancement

#44 panelQA
  Lib/src/gui/entity/component/PanelComponentQA.java
Labels: enhancement

#45 panelWW
  Lib/src/gui/entity/component/PanelComponentWW.java
Labels: enhancement

#46 table model PT
  Lib/src/gui/entity/component/TemplatePT.java
Labels: enhancement

#47 TABLE MODEL QA
  Lib/src/gui/entity/component/TemplateQA.java
Labels: enhancement

#48 TABLE MODEL WW
  Lib/src/gui/entity/component/TemplateWrittenWorks.java
Labels: enhancement

#49 Add DialogUpdateSubject.java (Update Dialog)
  Lib/src/gui/entity/subject/DialogUpdateSubject.java
Labels: good first issue

#54 Create Domain: WrittenWorks.java
  Lib/src/domain/WrittenWorks.java
Labels: enhancement

#55 Create Repository: CRUDWrittenWorks.java
  Lib/src/repository/CRUDWrittenWorks.java
Labels: enhancement

#57 Create Repository: CRUDQuarterlyAssessment.java
  Lib/src/repository/CRUDQuarterlyAssessment.java
Labels: enhancement

#56 Create domain: QuarterlyAssessment.java
  Lib/src/domain/QuarterlyAssessment.java
Labels: enhancement

#60 GUI Finalization
  Lib/src/EMarkaApplication.java
  Lib/src/gui/FrameMain.java
Labels: enhancement

#62 ENHANCEMENT OF COMPONENTS
  Lib/src/EMarkaApplication.java
  Lib/src/connection/DatabaseConnection.java
  Lib/src/domain/QuarterlyAssessment.java
  Lib/src/domain/Student.java
  Lib/src/gui/FrameMain.java
  Lib/src/gui/entity/component/DialogCreatePT.java
  Lib/src/gui/entity/component/DialogCreateQA.java
  Lib/src/gui/entity/component/DialogCreateWW.java
  Lib/src/gui/entity/component/PanelComponentPT.java
  Lib/src/gui/entity/component/PanelComponentQA.java
  Lib/src/gui/entity/component/PanelComponentWW.java
  Lib/src/gui/entity/component/TemplatePT.java
  Lib/src/gui/entity/component/TemplateQA.java
  Lib/src/gui/entity/component/TemplateQuarterlyAssessment.java
  Lib/src/gui/entity/component/TemplateWW.java
  Lib/src/gui/entity/grade/DialogViewGrade.java
  Lib/src/gui/entity/grade/PanelGradeManagement.java
  Lib/src/gui/entity/grade/TemplateGrade.java
  Lib/src/gui/entity/student/DialogCreateStudent.java
  Lib/src/gui/entity/student/DialogUpdateStudent.java
  Lib/src/gui/entity/student/PanelStudentManagement.java
  Lib/src/gui/entity/student/TemplateStudent.java
  Lib/src/gui/entity/subject/DialogCreateSubject.java
  Lib/src/gui/entity/subject/DialogUpdateSubject.java
  Lib/src/gui/entity/subject/PanelSubjectManagement.java
  Lib/src/repository/CRUDPerformanceTasks.java
  Lib/src/repository/CRUDQuarterlyAssessment.java
  Lib/src/repository/CRUDStudent.java
  Lib/src/repository/CRUDWrittenWorks.java
Labels: enhancement

#66 Hotfix Version 1.2 Panels
  Lib/src/connection/DatabaseConnection.java
  Lib/src/gui/entity/grade/PanelGradeManagement.java
  Lib/src/gui/entity/student/PanelStudentManagement.java
  Lib/src/gui/entity/subject/PanelSubjectManagement.java
Labels: enhancement

#69 Add Data Access Objects
  Lib/src/repository/CRUDGrade.java
  Lib/src/repository/GradePTDAO.java
  Lib/src/repository/GradeQADAO.java
  Lib/src/repository/GradeWWDAO.java
Labels: good first issue

#71 hotfix gui
  Lib/src/EMarkaApplication.java
  Lib/src/gui/entity/grade/PanelGradeManagement.java
  Lib/src/gui/entity/grade/TemplateGrade.java
  Lib/src/gui/entity/subject/TemplateSubject.java
Labels: enhancement

#72 Update domains and fix bugs
  Lib/src/domain/Grade.java
  Lib/src/domain/PerformanceTasks.java
  Lib/src/domain/QuarterlyAssessment.java
  Lib/src/domain/Student.java
  Lib/src/domain/Subject.java
  Lib/src/domain/WrittenWorks.java
Labels: enhancement

#73 Update Repository
  Lib/src/repository/CRUDGrade.java
  Lib/src/repository/GradePTDAO.java
  Lib/src/repository/GradeQADAO.java
  Lib/src/repository/GradeWWDAO.java
Labels: enhancement

#78 Enhance and debug GUI Grade
  Lib/src/gui/entity/grade/DialogViewGrade.java
  Lib/src/gui/entity/grade/PanelGradeManagement.java
  Lib/src/gui/entity/grade/TemplateGrade.java
Labels: enhancement

#79 Debug DAO
  Lib/src/repository/GradePTDAO.java
  Lib/src/repository/GradeQADAO.java
  Lib/src/repository/GradeWWDAO.java
Labels: bug

#80 Enhance Grade and CRUDGrade
  Lib/src/domain/Grade.java
  Lib/src/repository/CRUDGrade.java
Labels: bug

#81 Enhance Repository
  Lib/src/repository/CRUDGrade.java
  Lib/src/repository/CRUDPerformanceTasks.java
  Lib/src/repository/CRUDQuarterlyAssessment.java
  Lib/src/repository/CRUDWrittenWorks.java
Labels: duplicate

#82 Enhance Grade Function
  Lib/src/domain/Grade.java
  Lib/src/gui/entity/grade/DialogViewGrade.java
  Lib/src/gui/entity/grade/PanelGradeManagement.java
Labels: documentation

#83 Enhancement of Grade Function
  Lib/src/gui/entity/grade/DialogViewGrade.java
  Lib/src/gui/entity/grade/PanelGradeManagement.java
  Lib/src/repository/CRUDGrade.java
Labels: enhancement

#85 Enhance DialogViewGrade
  Lib/src/gui/entity/grade/DialogViewGrade.java
Labels: enhancement

#86 enhancement of View Grade
  Lib/src/gui/entity/grade/DialogViewGrade.java
  Lib/src/gui/entity/grade/PanelGradeManagement.java
Labels: enhancement

#87 Enhancement of Main Frame + New Welcome Panel
  Lib/src/gui/FrameMain.java
  Lib/src/gui/PanelWelcome.java
Labels: enhancement

#88 Enhance of Dialog
  Lib/src/gui/entity/grade/DialogViewGrade.java
Labels: enhancement

#89 Updated Database
  SQLDump(Import This)/Dump20210221/student_db_gradept.sql
  SQLDump(Import This)/Dump20210221/student_db_gradeqa.sql
  SQLDump(Import This)/Dump20210221/student_db_gradeww.sql
  SQLDump(Import This)/Dump20210221/student_db_performancetasks.sql
  SQLDump(Import This)/Dump20210221/student_db_quarterlyassessment.sql
  SQLDump(Import This)/Dump20210221/student_db_student.sql
  SQLDump(Import This)/Dump20210221/student_db_subject.sql
  SQLDump(Import This)/Dump20210221/student_db_writtenworks.sql
  SQLDump(Import This)/student_db.sql
Labels: enhancement

#90 Hotfix Frame And Grade Dialog
  Lib/src/gui/FrameMain.java
  Lib/src/gui/entity/grade/DialogViewGrade.java
Labels: bug

#96 finalization of Dialog Grade
  Lib/src/gui/entity/grade/DialogViewGrade.java
  Lib/src/gui/entity/grade/PanelGradeManagement.java
Labels: bug, enhancement
